version: "3.8"

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgresDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_crud
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: 256mb
    restart: unless-stopped

volumes:
  postgres_data: